version: '3'

services:
  webapi:
    build:
      args:
        - CONFIG=test_config.py
        - REQUIREMENTS=requirements.test.txt
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=development
      - FLASK_APP=env.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8000
    entrypoint: ./run_app.sh
    volumes:
      - ./home_io_backend:/opt/home_io_backend/home_io_backend
  
  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  avatars:
    driver: local